### ISSUE TITLE
Can This one be hosted on apache ?

### ISSUE THREAD

**Issue by rspk65** [kepi/IcingaChromedStatus#30]
Hi  i liked this application and i want to pull data from our local nagios system and display using this application in another browser. Is there a way to host this on local apache server ? kindly please help me on this

**Comment by kepi** [comment]
You simply have to somehow make your local nagios system available from remote computer where you want to use this extension.

There are different ways to do this - create VPN, redirect ports, make tunel over SSH etc but all are out of scope of this extension. You simply need to make your local nagios accessible through classic browser and then you can get cgi address to use in Icinga Status.
