### ISSUE TITLE
hide services from acked hosts

### ISSUE THREAD

**Issue by jesusch** [kepi/IcingaChromedStatus#31]
also this project seems dead :)

while installing the extension I noticed that 1 host which is acknowledged down, all of its services are still shown as seperate critical items

**Comment by kepi** [comment]
Hello, you are absolutely right, this project is kind of dead. I'm still thinking about some kind of revival but with new icingaweb2 it is not so urgent for me :)

Anyway I do not plan to implement hiding services from acked hosts as icinga/nagios is handling this by their own. When you set downtime to host, you have checkbox to "set downtime to all services" on that host. And yes, I probably don't get why this is even option too :)
